setConfig(document.currentScript,'{"name":"اتصالات باب الكبير - المركز الرئيسي"},
setConfig(document.currentScript,'{"name":"بقالة ابراهيم برغش - داخل سوق القات ( 24 ساعة )"},
setConfig(document.currentScript,'{"name":"بقالة محمد علي - راس الشنيني - على الدرج الموصلة لشارع 26"},
setConfig(document.currentScript,'{"name":"بقالة الشرعبي - حارة اسحاق - الميدان"},
setConfig(document.currentScript,'{"name":"واتس فون - شارع 26 - جوار فتحة المخلوله"},
setConfig(document.currentScript,'{"name":"بقالة ابو راكان - امام مسجد جمال الدين"},
setConfig(document.currentScript,'{"name":"فرم كعك المر - مقابل اتصالات باب الكبير"},
setConfig(document.currentScript,'{"name":"بقالة سعدي - مقابل حوش هزاع"},
setConfig(document.currentScript,'{"name":"بقالة محمد علي - تحت قسم شرطة باب الكبير"},
setConfig(document.currentScript,'{"name":"بقالة باسم - شارع الجمهوريه"},
setConfig(document.currentScript,'{"name":"بقالة عبدالله العديني - مقابل مقهى ابن الحاج"},
setConfig(document.currentScript,'{"name":"بقالة البعداني - مقابل فرم الروتي"},
setConfig(document.currentScript,'{"name":"بقالة تصحيح - مقابل اتصالات نجم المدينة"},
setConfig(document.currentScript,'{"name":"بقالة امين الصبري - مقابل جسر وادي المدام"},